[project]
name = "litestar_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litestar[standard]>=2.14.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
